### ISSUE TITLE
writing string spectrum attribute in error

### ISSUE THREAD

**Issue by c2sluli** [tango-controls/labview-binding#11]
Hi,

I can't write in a string spectrum attribute, I have an error in _TangoWriteStringSpectrumAttribute.vi.
![Erreur write string spectrum](https://user-images.githubusercontent.com/39738273/74037288-421c8280-49be-11ea-9609-53179130a3e0.jpg)

best regards

**Comment by nleclercq** [comment]
Problem confirmed.
I had a crash while trying to reproduce the reported problem...

**Comment by nleclercq** [comment]
Crash fixed. 
See new ReadStringSpectrumAndImageAttributes.vi example.
