### ISSUE TITLE
support for later versions of gcc?

### ISSUE THREAD

**Issue by kalzso** [tango-controls/labview-binding#3]
Hello,

I'm using Ubuntu 16.04, and I would like to compile the latest labview-binding. Unfortunatelly there is no gcc-4.3 available for Ubuntu 16.04, so I'm stuck here..
Any help or suggestion would be appreciated!

**Comment by nleclercq** [comment]
Hi @kalzso, 
I just added a precompiled version of the binding so that you can give it a try - see vis/tango_binding.so. All you have to do is to pull it from your git clone. Hope it will work for you.
In case it doesn't, you will have to recompile the whole tango software chain + the binding itself.
See [how to compile the binding for linux](https://github.com/tango-controls/labview-binding).
n.

**Comment by EastEriq** [comment]
For the record, you added the 32bit .so and the 64bit .dll. The other two combinations may be useful too. LV2014 linux was only 32bit, but later versions are 64 too. Conversely, LV windows has many more toolboxes, but several are limited to 32bit, which is therefore a forced choice.
Just saying, anyway. Precompiled libraries are big and one cannot include everything. A snapshot of the repo is currently above half a GB.

**Comment by nleclercq** [comment]
Right. The idea was just to provide binaries for the main configurations. BTW, I have no windows/32 nor linux/64 versions of LabVIEW.

**Comment by nleclercq** [comment]
@EastEriq How did you do finally? You recompiled the shared lib (or dll) or used the provided one?

**Comment by EastEriq** [comment]
For now I deflected the problem and kept copying them from release 3.0.3 (there the dll is 32bit), which is not the right thing to do if the c++ evolves.
BTW LV2014/linux was only 32bit, 64bit versions were available only from 2015 on, IIRC. A notable reason for me to be stuck with windows/32bit is the [DSC module](http://www.ni.com/labview/labviewdsc/).

**Comment by kalzso** [comment]
I used the compiled version, and it seems to work, thanks!

**Comment by nleclercq** [comment]
>  A notable reason for me to be stuck with windows/32bit is the DSC module.

It's a shame to have the DSC module only available for Windows. I really don't why BTW. Due to the underlying OPC stuffs maybe?

**Comment by EastEriq** [comment]
It leverages on the Shared Variable Engine which is only windows. There is an OPC connector but this is just a plugin I think. I don't understand why only 32 though.
