### ISSUE TITLE
Connection without DB server

### ISSUE THREAD

**Issue by cvniekerk** [tango-controls/labview-binding#7]
Is it possible to directly connect to a device server without a DB server running. I managed to connect by specifying the following format in the "device name" field: 
ip_address:10000/a/b/c#dbase=no
But then the LV Tango Library still wants to reference a real TANGO_HOST location. I then just give it a fake Tango Database and everything works, but this is not ideal. For unit testing this requires the setup of some kind of Tango Database somewhere, even though it is not really used.

**Comment by nleclercq** [comment]
@cvniekerk Ok, we're are talking about a LabVIEW client trying to connect to a (C++, Java or Python) Tango device started with the following method: `myserver myinstance_name -ORBendPoint giop:tcp:ip_address:10000 -nodb -dlist a/b/c `. Right?

**Comment by cvniekerk** [comment]
Yes, this is correct, except that I do start the device with a database file, and without the last 2 parameters as follows:
`myserver myinstance_name -file=server_file -ORBendPoint giop:tcp:ip_address:10000`

**Comment by nleclercq** [comment]
Hum... I don't see where the error comes from. I'm afraid it's not related to the LabVIEW binding. I suspect that what you observe is the expected Tango behavior.  Could you provide me with the exact error message you get when the `TANGO_HOST` env. var. is undefined? Would you also mind trying with another Tango client in the same environment? A python one for instance.

**Comment by cvniekerk** [comment]
Here is the response when trying to connect to a device without the `TANGO_HOST` defined:
`
Error -1 occurred at tango.lvlib:_TangoExceptionToLabviewError.vi
Possible reason(s):
[TangoDeviceAttributesList.vi]  - ERROR - API_TangoHostNotSet - TANGO_HOST env. variable not set, set it and retry (e.g. TANGO_HOST=<host>:<port>) - Database::Database - ERROR - attribute_list_query failed - failed to get device attributes list - LvDeviceProxy::get_device_interface - ERROR - object instanciation failed - LvDeviceProxy instanciation failed [Tango exception caught] - LvDeviceProxyRepository::device_proxy
Complete call chain:
     tango.lvlib:_TangoExceptionToLabviewError.vi
     tango.lvlib:_TangoDeviceAttributesList.vi
     EMSS SPF SHIELD.vi
`
And with any random TANGO_HOST defined, it does connect.

**Comment by nleclercq** [comment]
Ok. The error comes from Tango itself and not from the LabVIEW binding (see <tango-src>/lib/cpp/client/dbapi_base.cpp). Sorry but I can't do anything to fix or workaround the problem. 

I asked the Tango kernel gurus to have a look to your post.

**Comment by bourtemb** [comment]
Hi,

Could you try using the following syntax?
tango://ip_address:10000/a/b/c#dbase=no

instead of 
ip_address:10000/a/b/c#dbase=no

Hoping this helps,
Reynald

**Comment by nleclercq** [comment]
Thanks @bourtemb. I'm afraid I bothered you with this problem for nothing. I think I located it. It's in the binding in fact. When a proxy to a tango device is instantiated, the binding tries to retrieve each attribute alias from the tango db - an action which itself requires the TANGO_HOST to be defined. Just wrote a fix (no db = no alias support). Stay tuned…

**Comment by bourtemb** [comment]
Cool! Thanks for the update!

**Comment by nleclercq** [comment]
@cvniekerk Could you please replace vis/tango_binding.dll with the one attached to this post and see if it fixes the problem? 

[tango_binding.zip](https://github.com/tango-controls/labview-binding/files/2105413/tango_binding.zip)

**Comment by cvniekerk** [comment]
I'm running 32-bit LabVIEW 2015. Is this by any chance a 64-bit library?
LabView says that the selected library is not valid.

**Comment by nleclercq** [comment]
It's indeed a x64 binary. I can't produce a x86 one with my env.

**Comment by cvniekerk** [comment]
Hmm, still trying to compile for my environment, getting all the necessary tools...
I previously used the x86 released binary package from the tango-controls website. (tango-binding-3.0.0-for-labview-2015-windows-x86.zip)
I'll let you know when I get it going.

**Comment by nleclercq** [comment]
Be sure to have a look the [README](https://github.com/tango-controls/labview-binding).
It contains critical info for anyone trying to recompile the binding.
The [releases page](https://github.com/tango-controls/labview-binding/releases) contains at a link to the [windows runtime](https://github.com/tango-controls/labview-binding/releases/download/v3.1.1/tango-for-windows.zip) - which is required to recompile the binding and could save hours of your precious time.

**Comment by cvniekerk** [comment]
Thanks for the notes and references. I did work through all instructions. 
At first my Visual Studio 2017 had a lot of missing std files which I had to install & manually include in the project. 
Then I got a few linker errors ([LNK2001](https://msdn.microsoft.com/en-us/library/f6xx1b1z.aspx), [LNK4006](https://stackoverflow.com/questions/37922117/stdbasic-ostringstream-exported-by-boost-unit-test-framework-dll-results-in-an) & [LNK1281](https://stackoverflow.com/questions/10599940/module-unsafe-for-safeseh-image-c/12980627)), but eventually managed to compile this morning. I will test it now.

**Comment by cvniekerk** [comment]
Compiled for LV2015 & LV2017 (both x86), I get the same error in LabView when trying to connect to the device server:
![image](https://user-images.githubusercontent.com/14199959/41709837-7f7daf8c-7544-11e8-9a6b-0562092da27b.png)
With debug enabled I get this from LabView:
![image](https://user-images.githubusercontent.com/14199959/41710502-185d8a14-7546-11e8-9004-c7f5f40886e4.png)

When compiling for LV2017 (64-bit) I get a linker error in Visual Studio:
`
1>LvDeviceServer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >(char const * const,unsigned __int64)" (__imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD_K@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl std::basic_stringbuf<char,struct std::char_traits<char>,class std::allocator<char> >::str(void)const " (?str@?$basic_stringbuf@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ)
`
...
`
1>../../vis/tango_binding.dll : fatal error LNK1120: 5 unresolved externals
`
Any suggestions?

**Comment by cvniekerk** [comment]
There are a few extra warnings on a successful build [Release] [Win32] with Platform Toolset=Visual Studio 2015 (v140). (Also same for 2017 (V141)) 
Here is the full output:

`
1>------ Build started: Project: TangoBindingForLabview, Configuration: Release Win32 ------
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>DataAdapter.cpp
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>DeviceGroup.cpp
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>DeviceGroupRepository.cpp
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>Endianness.cpp`
`
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>ErrorStack.cpp`
`
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>EventManager.cpp`
`
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>LvDevice.cpp`
`
1>cl : Command line warning D9035: option 'Zc:forScope-' has been deprecated and will be removed in a future release`
`
1>LvDeviceClass.cpp`
`1>LvDeviceClassFactory.cpp`
`1>LvDeviceImpl.cpp`
`1>LvDeviceProxy.cpp`
`1>LvDeviceProxyRepository.cpp`
`1>LvDeviceRepository.cpp`
`1>LvDeviceServer.cpp`
`1>ObjectManager.cpp`
`1>TangoBinding.cpp`
`1>ThreadSafeDeviceProxy.cpp`
`1>parser.cpp`
`1>tinyxml2.cpp`
`1>DeviceGroup.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>DeviceGroupRepository.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>Endianness.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>ErrorStack.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>EventManager.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDevice.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceClass.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceClassFactory.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceImpl.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceProxy.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceProxyRepository.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceRepository.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>LvDeviceServer.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>ObjectManager.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>TangoBinding.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>ThreadSafeDeviceProxy.obj : warning LNK4006: "class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > & __cdecl operator<<(class std::basic_ostringstream<char,struct std::char_traits<char>,class std::allocator<char> > &,class Tango::DevFailed const &)" (??6@YAAAV?$basic_ostringstream@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) already defined in DataAdapter.obj; second definition ignored`
`1>   Creating library .\Releasex86/tango_binding.lib and object .\Releasex86/tango_binding.exp`
`1>../../vis/tango_binding.dll : warning LNK4088: image being generated due to /FORCE option; image may not run`
`1>TangoBindingForLabView.vcxproj -> D:\github\labview-binding\windows\msvc12\..\..\vis\tango_binding.dll`
`1>TangoBindingForLabView.vcxproj -> ../../vis/tango_binding.pdb (Full PDB)`
`1>Done building project "TangoBindingForLabView.vcxproj".`
`========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by nleclercq** [comment]
These linker warnings can be safely ignored. I spent some time trying to figure out where they come from and I think I can't do anything to fix it cause it seems to be  due to the way std::basic_ostringstream specializations are injected into the binary.  Anyway, it's not a critical problem and the LabVIEW binding works smoothly. 

On the other hand, I note the deprecation of the "Zc:forScope-" option. My compiler version doesn't raise nay warning about it. Thanks for reporting.

So, you finally have something working?

**Comment by nleclercq** [comment]
BTW, how did you fixed the following linker error: "../../vis/tango_binding.dll : fatal error LNK1120: 5 unresolved externals"? See your n-2 post.

**Comment by cvniekerk** [comment]
No, on a successful build I still get the Labview exception Error 1097 as displayed above. (when trying to connect to the device server)

**Comment by nleclercq** [comment]
I see. I would try in release mode instead of debug. The latter is sometimes a bit extreme in detecting problems.

**Comment by nleclercq** [comment]
What should we do with this issue? Work on it? Close it?

**Comment by cvniekerk** [comment]
I will try and work on it next week in order to test it on my system.

**Comment by cvniekerk** [comment]
Hi, 
You can close this issue now, thank you.
I just tested the x64 binary tango_binding and it work on my LabView 2017 64-bit version. I can connect to a local tango device server without declaring a specific TANGO_HOST variable.

I don't know if the x86 version would work though, as I no longer use the LabView 32-bit version.

**Comment by risbil** [comment]
Hi, 

@ cvniekerk you wrote:
When compiling for LV2017 (64-bit) I get a linker error in Visual Studio:
1>LvDeviceServer.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >(char const * const,unsigned __int64)" (__imp_??0?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEAA@QEBD_K@Z) referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl std::basic_stringbuf<char,struct std::char_traits<char>,class std::allocator<char> >::str(void)const " (?str@?$basic_stringbuf@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@QEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@XZ)
...
1>../../vis/tango_binding.dll : fatal error LNK1120: 5 unresolved externals

Do you remember how you managed to fix this error?

I am using LV 2019 (64 bit), tango binding 3.2, tango for windows  and I have installed TangoSetup-9.2.2_win64. I keep getting the linker errors in the LvDeviceServer.

Thank you

**Comment by nleclercq** [comment]
I don't remember I had to fix this specific linker error. I used to have some duplicated symbols - a linker error that could be ignored using a dedicated option. 

Are you sure to have all the required libs listed at link stage ?

**Comment by risbil** [comment]
Dear Mr. Leclercq,

thank you for your input.
I think that I have all the correct libs linked.

But, still no luck :)

Best regards
Biljana R.

**Comment by nleclercq** [comment]
Biljana,
It seems that you switched from LV2017 to 2019 Right ?
Does the compilation completes successfully with LV2017 ?

**Comment by risbil** [comment]
Dear Mr. Leclercq,

I tried to use LV 2017 64bit, and I got the same result.

Best Regards
Biljana

**Comment by nleclercq** [comment]
Biljana,
Could you please compress (i.e. zip) your C:\Program Files\National Instruments\LabVIEW 201x\cintools directory and attach it to you next reply. Thanks.

**Comment by risbil** [comment]
Dear,

please see attachments.

Best Regards
Biljana

 cintools-LV17-64bit.zip
<https://drive.google.com/file/d/1FaRBrDNDAfWJAC0JYafUr2azo45_G7sg/view?usp=drive_web>

 cintools-LV19-64bit.zip
<https://drive.google.com/file/d/1-Y2D0uKankmnNo-s4yHtqcLg3ZR6ERPU/view?usp=drive_web>

**Comment by nleclercq** [comment]
Attached is a full binary distribution compiled with MSVC12 against your 2019 cintools. The compilation completed smoothly so I suspect that the problem comes from the MSVC version you're using. I'm afraid you would have to recompile the whole Tango software chain (full runtime) with that MSVC version. Anyway, please give the attached distribution a try and let me know.

[tango-binding-3.2.0-for-labview-2019-windows-x64.zip](https://github.com/tango-controls/labview-binding/files/3966812/tango-binding-3.2.0-for-labview-2019-windows-x64.zip)

**Comment by risbil** [comment]
Dear,

thank you for the file. The issue was with the visual studio version. I had
to install the 2012.

So, now I have a working 64bit tango binding.

Can I use the tango binding 3.2.0 for the compiling a 32 bit version of the
tango-binding.dll.
If yes, which tango version should I install (the
TangoSetup-8.1.2b_win32.exe) ?

Best  regards
Biljana

**Comment by nleclercq** [comment]
The binding works in both 32 and 64 bits mode. The only thing to do is to modify the env. setup file in order to point to your Tango win32 distribution, launch MSVC12 (using the dedicated script), select the "Win32" configuration and recompile the project.  

Yes, TangoSetup-8.1.2b_win32.exe is the lastest win32 version. It's the recommended one.

**Comment by risbil** [comment]
Hello,

sorry to disturb you again, but I am not able to make the build for the
32bit version.
If I send you the LV 2019 32bit cintools files, can you try it, please?

Best Regards
Biljana Ristovska

**Comment by nleclercq** [comment]
Ok. Let's try.

**Comment by risbil** [comment]
Thank you.
If you are successful, please send me the project details, too.

Best Regards
Biljana

 cintools.zip
<https://drive.google.com/file/d/1aQMq1XOEAKbJk1czYmjpjF9-iLIeF35H/view?usp=drive_web>

**Comment by nleclercq** [comment]
Works for me (with msvc12).
I simply copied your cintools directory to %BINDING_PATH%\labview\2019\cintools-x32 and changed the compile-env-setup.bat file in order to take this location into account : 
set LV_ROOT32=%BINDING_PATH%\labview\2019
set LV_INC32=%LV_ROOT32%\cintools-x32
set LV_LIB32=%LV_ROOT32%\cintools-x32
SET LV_LIB32_LIST=labview.lib

**Comment by risbil** [comment]
Hello,

so I am getting truly desparate now.
I did all of that...

Can you send me at least the *.vcxproj file?

Thank you
Biljana

**Comment by nleclercq** [comment]
The *.vcxproj is the one from the git repo (untouched). 

Are you sure it doesn't compile ? There're plenty of warning (duplicate definitions) that can be safely ignore. The link stage is quite verbose. 

BTW, don't try to build anything else than the **Release** configuration (optimized version containing the debug symbols).

If if works, you should get something  like (sorry messages are in French) :  
```
$allocator@D@2@@std@@AAV01@ABVDevFailed@Tango@@@Z) déjà défini dans DataAdapter.obj ; seconde définition ignorée
> 1>     Création de la bibliothèque .\Releasex86/tango_binding.lib et de l'objet .\Releasex86/tango_binding.exp
> 1>../../vis/tango_binding.dll : warning LNK4088: image en cours de génération à cause de l'option /FORCE ; l'image risque de ne pas s'exécuter
> 1>  TangoBindingForLabView.vcxproj -> C:\mystuffs\dev\bindings\labview-binding@github\windows\msvc12\..\..\vis\tango_binding.dll
> ========== Rebuild All: 1 succeeded, 0 failed, 0 skipped =========
```

**Comment by nleclercq** [comment]
BTW, would you mind to tell me a couple of words about you're application?
Thanks.

**Comment by risbil** [comment]
Hello,



first of all, Nappy New Year.



Yes, I am sure it does not compile. To  recapitulate  , this is my
procedure (I tried Visual Studio 2010 and Visual Studio 2013)  :



- Download source code.zip from here
https://github.com/tango-controls/labview-binding/releases,  the 3.2.0
version.  Save it here: C:\github

- Install Tango 812 (download from here
https://sourceforge.net/projects/tango-cs/files/Previous_Releases/Tango8/TangoSetup-8.1.2b_win32.exe/download).
Installation is in folder: C:\github\labview-binding-3.2.0\runtime

- Then I downloaded tangoforwindows.zip. I copied the yat and yatfortango
to C:\github\labview-binding-3.2.0\runtime\tango\win32\include and
C:\github\labview-binding-3.2.0\runtime\tango\win32\lib.

- Edit the bat file, and manually set all the environmental values.

- Now, I open the project. I have errors about Tango Enums. I comment all
of these lines. (the tango 812.dll is an older version and is not fully
compatible with the source code).

- And then, a lot of linker errors.



What am I doing wrong?




Thank you

Biljana

**Comment by risbil** [comment]
Hello,

so my task is to help my client use labview-binding and create a device
server, use the publish-subscribe model and communicate with different
clients.

The idea is that the properties will be dynamically allocated (through
labview).


Have a nice day
Biljana

**Comment by nleclercq** [comment]
I see. Your runtime should be 9.2.x. Sorry I should have noticed that earlier. 
Please switch to : 
https://www.dropbox.com/s/b74wm6no5vuhwey/tango-for-windows.zip?dl=1

`::- runtime directory
set RUNTIME_PATH_X86=C:\mystuffs\dev\bindings\tango-9.2.2-dev-windows
set RUNTIME_PATH_X64=C:\mystuffs\dev\bindings\tango-9.2.2-dev-windows
::- .h
set RUNTIME_INC_X86=%RUNTIME_PATH_X86%\include
set RUNTIME_INC_X64=%RUNTIME_PATH_X64%\include
::- .lib
set RUNTIME_LIB_X86=%RUNTIME_PATH_X86%\lib\x86\tango-9.2.2-vc10
set RUNTIME_LIB_X64=%RUNTIME_PATH_X64%\lib\x64\tango-9.2.2-vc12
::- .dll
set RUNTIME_BIN_X86=%RUNTIME_PATH_X86%\lib\x86\tango-9.2.2-vc10
set RUNTIME_BIN_X64=%RUNTIME_PATH_X64%\lib\x64\tango-9.2.2-vc12
::- path
set PATH=%RUNTIME_BIN_X86%;%PATH%
set PATH=%RUNTIME_BIN_X64%;%PATH%
set PATH=%BINDING_PATH%\vis;%PATH%`

**Comment by nleclercq** [comment]
Is your client one of the ELI facilities ? Just curious :-)

**Comment by nleclercq** [comment]
Are you there ?

**Comment by risbil** [comment]
Hello,

yes, I am here.
I managed to compile the code. Now, I am trying to add dynamic attributes
to a device, through LabView.

Also, I am sorry, but my contract does not allow to discuss my customers or
any potential customers. I hope you understand that.

Thank you very much for your help and support,
Biljana

**Comment by nleclercq** [comment]
Ok.

BTW, you can't add a dynamic attribute to a DeviceServer implemented in LabVIEW. It's interface must be prefined in the associated .xmi file. In other word, there's no VI providing a way to dynamically add an attribute to a device written in LabVIEW. See "Writing a Tango Device Server in LabVIEW.pdf" for details. That's a limitation of the LabVIEW DeviceServer API.

**Comment by risbil** [comment]
Hello,

thanks for the input. I was hoping to find some workaround.
Is this limitation because of the LV DS behaviour, or just that it is still
not implemented?

Thank you
B.

**Comment by nleclercq** [comment]
It's not implemented will certainly not unless someone has some time to devote to this feature.

Wait... one thing you could do is to generate the .xmi file before instantiating the device - i.e. your LV app could generate the .xmi file and save to the appropriate "PathToPogoXmiFile" before launching the device using _DServerStart.vi. Just my 2 cents but could work as quite elegant workaround. The new limitation (or constraint) would be to have a previous knowledge of the full device interface at startup (i.e. you will not be able to modify the device interface once setup).

**Comment by risbil** [comment]
Hello,

this limitation is a problem for me.
Let's say that I am willing to try to implement this feature. Can you give
me some guidance on what to do?

My goal is to have a device server (in LabView) that:
- has unknown number of devices, and device can be added/removed during
runtime
- each device has unknown attributes and properties, again, that can be
added/removed during runtime.

Thanks
Biljana

**Comment by risbil** [comment]
Hello,

I am thinking of avoiding the dynamic attributes issue by restarting the
Device Server
Of course, this is also an issue in LabView. Restarting of Labview is not a
working solution.
Can you please explain me more LabView has to be restarted? For example,
unloading the dll did not work.
Also, can I avoid the issue of the restarting LV, if I work in Linux
environment?

Best Regards
Biljana

**Comment by nleclercq** [comment]
I see, you would like to have a single and ultra dynamic Tango device template for all physical devices...

The Tango model matches the classic OO approach : the instances of a given Tango class share the same interface. Tango provides a way to dynamically add/remove both attributes and commands but instances of a given class are still supposed to share the same interface (add/remove act at class level not instance level). 

Be aware, that could be a huge constraint when the instances are running into the same runtime context (i.e. several devices of a given class running into the same process) and that’s exactly what you want to do.

However, the labview binding uses a trick (changing the class name) to workaround this constraint to be able to (dynamically) populate devices interfaces at startup. 

So... if you want to add the feature to the binding you have to implement the add/remove Vis for both Command and Attribute and then write their C++ counterpart on the binding side. The rest of the game is quite straightforward cause the DeviceServer class of the Tango C++ API contains the required methods. 
 
BTW, you can add/remove commands and attributes from a device interface not properties. 

Good luck. 

(Please open a dedicated issue if you want to go further on this topic.)

**Comment by nleclercq** [comment]
The “restarting” constraint conned from the C++ API and there’s no workaround. Tango deviceserver model has been written to run into the context of a standalone C++ process (application) and not into a C++ dll.

**Comment by nleclercq** [comment]
I doubt that unloading the dll will work due to dependencies against other dlls (like omniorb).

**Comment by nleclercq** [comment]
BTW, restarting LV is required at dev stage.

**Comment by nleclercq** [comment]
I should have let the binding a pure client platform. Writing ds in lv is not a good idea. Moreover, NI is changing everything (LV-NG) and someone will have to rewrite the binding from scratch. Switch to C++ !

**Comment by nleclercq** [comment]
BTW, isn't your actual first name Birgit... Same kind of requests/needs, same kind of attitude.

**Comment by risbil** [comment]
Hello,

No, it really isn't.
Really strange question.

Have a nice day
Biljana

**Comment by nleclercq** [comment]
Deleted off topic exchanges.
