### ISSUE TITLE
license applied to this repo

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/labview-binding#9]
Hi Nicolas, 
reading the repositories of tango-controls, I've noticed there no license is specified here.
What is the license applied to this soft? I imagine perhaps  there could be some conflict between labview license and GPL?
Happy new year

**Comment by nleclercq** [comment]
Hi Philippe,
I'm almost one year late :-)
We don't distribute any binary coming from NI (the code is compiled against NI static libs). Moreover, the binding is totally useless without a valid Labview copy (i.e. a valid NI licence). I think we could apply the LGPL to this project (i.e. same as Tango itself).

**Comment by PhilLAL** [comment]
Hi Nicolas, 
hope you enjoyed this year :) 
I just added a LICENSE.md with LGPL, I let you merge if it's ok with you.

**Comment by nleclercq** [comment]
Thanks for your contribution.
